
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_client.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os


class UiFactory:
    """Factory utilities for building widgets consistently.
    Composed into Ui_client to reduce repetition while preserving behavior.
    """

    def __init__(self, ui):
        self.ui = ui  # access shared fonts/styles like _font9 and _btn_style

    def make_slider(self, parent, name, geom, orientation, minimum=None, maximum=None, value=None, set_font=False):
        slider = QtWidgets.QSlider(parent)
        slider.setGeometry(QtCore.QRect(*geom))
        slider.setStyleSheet(self.ui._btn_style)
        if minimum is not None:
            slider.setMinimum(minimum)
        if maximum is not None:
            slider.setMaximum(maximum)
        if value is not None:
            slider.setProperty("value", value)
        slider.setOrientation(orientation)
        slider.setObjectName(name)
        if set_font:
            slider.setFont(self.ui._font9)
        return slider

    def make_button(self, parent, name, geom):
        btn = QtWidgets.QPushButton(parent)
        btn.setGeometry(QtCore.QRect(*geom))
        btn.setFont(self.ui._font9)
        btn.setStyleSheet(self.ui._btn_style)
        btn.setObjectName(name)
        return btn

    def make_radio(self, parent, name):
        rb = QtWidgets.QRadioButton(parent)
        rb.setFont(self.ui._font9)
        rb.setStyleSheet(self.ui._btn_style)
        rb.setObjectName(name)
        return rb

    def create_label(self, parent, name, text, geom):
        label = QtWidgets.QLabel(parent)
        label.setGeometry(QtCore.QRect(*geom))
        label.setFont(self.ui._font9)
        label.setStyleSheet("font: 10pt \"Arial\";")
        label.setText(text)
        label.setAlignment(QtCore.Qt.AlignCenter)
        label.setObjectName(name)
        return label

    def create_slider(self, parent, name, geom, orientation, minimum, maximum, value):
        slider = QtWidgets.QSlider(parent)
        slider.setGeometry(QtCore.QRect(*geom))
        slider.setStyleSheet(self.ui._btn_style)
        slider.setMinimum(minimum)
        slider.setMaximum(maximum)
        slider.setProperty("value", value)
        slider.setOrientation(orientation)
        slider.setObjectName(name)
        return slider

    def create_radio_button(self, parent, name, text, geom):
        rb = QtWidgets.QRadioButton(parent)
        rb.setGeometry(QtCore.QRect(*geom))
        rb.setFont(self.ui._font9)
        rb.setStyleSheet(self.ui._btn_style)
        rb.setText(text)
        rb.setObjectName(name)
        return rb

    def create_line_edit(self, parent, name, text, geom):
        le = QtWidgets.QLineEdit(parent)
        le.setGeometry(QtCore.QRect(*geom))
        le.setFont(self.ui._font9)
        le.setStyleSheet("font: 10pt \"Arial\";")
        le.setText(text)
        le.setAlignment(QtCore.Qt.AlignCenter)
        le.setObjectName(name)
        return le


class SetupUI:
    """
    Builder class that constructs the UI by composing widgets in logical sections.
    
    This class breaks down the UI setup into smaller, focused methods for better
    maintainability and readability. Each method handles a specific section of the UI.
    """
    
    def __init__(self, ui):
        """Initialize the UI builder with a reference to the parent UI.
        
        Args:
            ui: Reference to the parent Ui_client instance
        """
        self.ui = ui
        self._fx = None  # Will be set in build()
    
    def build(self, client):
        """Build and configure the entire UI.
        
        This is the main entry point that orchestrates the UI construction.
        
        Args:
            client: The main window widget
        """
        self._prepare_client_window(client)
        self._initialize_shared_resources()
        
        # Create UI sections in logical order
        self._create_video_display(client)
        self._create_control_buttons(client)
        self._create_status_indicators(client)
        self._create_sliders_and_controls(client)
        self._create_mode_selectors(client)
        self._create_power_indicators(client)
        
        # Finalize UI setup
        self._setup_z_order()
        self.ui.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)
    
    def _prepare_client_window(self, client):
        """Configure the main window properties."""
        client.setObjectName("client")
        client.resize(1000, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        client.setFont(font)
        
        # Load external styles if available
        self._load_external_styles(client)
        
        # Set locale
        client.setLocale(QtCore.QLocale(
            QtCore.QLocale.English, 
            QtCore.QLocale.UnitedStates
        ))
    
    def _load_external_styles(self, client):
        """Load styles from external QSS files if available."""
        try:
            styles_dir = os.path.join(os.path.dirname(__file__), "styles")
            if os.path.exists(styles_dir):
                qss_contents = []
                for name in sorted(os.listdir(styles_dir)):
                    if name.endswith(".qss"):
                        with open(os.path.join(styles_dir, name), "r", encoding="utf-8") as f:
                            qss_contents.append(f.read())
                if qss_contents:
                    client.setStyleSheet("\n".join(qss_contents))
        except Exception as e:
            print(f"Warning: Could not load styles: {e}")
    
    def _initialize_shared_resources(self):
        """Initialize shared resources like fonts and geometry."""
        self.ui._init_fonts()
        self.ui._init_geo()
        self._fx = UiFactory(self.ui)
    
    def _create_video_display(self, client):
        """Create the main video display area."""
        self.ui.Video = self._fx.create_label(client, "Video", "", (10, 10, 600, 450))
        self.ui.Video.setFont(QtGui.QFont("Arial", 9))
        self.ui.Video.setStyleSheet("font: 10pt \"Arial\";")
        self.ui.Video.setText("")
        self.ui.Video.setObjectName("Video")
    
    def _create_control_buttons(self, client):
        """Create the control buttons in the top section."""
        # Connection controls
        self.ui.Button_Calibration = self._fx.make_button(client, "Button_Calibration", (40, 470, 90, 30))
        self.ui.lineEdit_IP_Adress = self._fx.create_line_edit(client, "lineEdit_IP_Adress", "192.168.1.121", (160, 470, 90, 30))
        self.ui.Button_Connect = self._fx.make_button(client, "Button_Connect", (280, 470, 90, 30))
        self.ui.Button_Video = self._fx.make_button(client, "Button_Video", (400, 470, 90, 30))
        
        # Function buttons
        self.ui.Button_Relax = self._fx.make_button(client, "Button_Relax", (520, 470, 90, 30))
        self.ui.Button_IMU = self._fx.make_button(client, "Button_IMU", self.ui._geo["Button_IMU"])
        self.ui.Button_Sonic = self._fx.make_button(client, "Button_Sonic", self.ui._geo["Button_Sonic"])
        self.ui.Button_LED = self._fx.make_button(client, "Button_LED", self.ui._geo["Button_LED"])
        self.ui.Button_Buzzer = self._fx.make_button(client, "Button_Buzzer", self.ui._geo["Button_Buzzer"])
        
        # Face recognition controls
        self.ui.Button_Face_ID = self._fx.make_button(client, "Button_Face_ID", (40, 510, 90, 30))
        self.ui.Button_Face_Recognition = self._fx.make_button(client, "Button_Face_Recognition", (630, 355, 90, 30))
    
    def _create_status_indicators(self, client):
        """Create status and sensor readout labels."""
        # IMU/Attitude indicators
        self.ui.label_6 = self._fx.create_label(client, "label_6", "Roll", (913, 75, 30, 20))
        self.ui.label_attitude = self._fx.create_label(client, "label_attitude", "Attitude", (801, 185, 60, 20))
        self.ui.label_roll = self._fx.create_label(client, "label_roll", "0", (911, 255, 30, 20))
        self.ui.label_Y = self._fx.create_label(client, "label_Y", "Y", (891, 285, 30, 20))
        
        # Position indicators
        self.ui.label_X = self._fx.create_label(client, "label_X", "X", (891, 315, 30, 20))
        self.ui.label_Z = self._fx.create_label(client, "label_Z", "Z", (891, 345, 30, 20))
        
        # Sonic sensor indicator
        self.ui.label_sonic = self._fx.create_label(client, "label_sonic", "0", (930, 180, 40, 20))
    
    def _create_sliders_and_controls(self, client):
        """Create sliders and related controls."""
        # Head control sliders
        self.ui.slider_head_1 = self._fx.create_slider(client, "slider_head_1", (245, 765, 160, 20), QtCore.Qt.Horizontal, 0, 180, 90)
        self.ui.slider_head_2 = self._fx.create_slider(client, "slider_head_2", (245, 790, 160, 20), QtCore.Qt.Horizontal, 0, 180, 90)
        
        # Other sliders...
        # [Previous slider creation code would go here]
        
        # Add slider value labels
        self._create_slider_labels(client)
    
    def _create_slider_labels(self, client):
        self.ui.label_head_1 = self._fx.create_label(client, "label_head_1", "90", (410, 765, 30, 20))
        self.ui.label_head_2 = self._fx.create_label(client, "label_head_2", "90", (410, 790, 30, 20))
    
    def _create_mode_selectors(self, client):
        """Create radio buttons for mode selection."""
        # Action mode radios
        self._create_radio_group(
            client, "action", 
            ["Radio_Action_1", "Radio_Action_2", "Radio_Action_3"],
            ["Action 1", "Action 2", "Action 3"],
            (40, 600, 120, 20), 120, 0, 1)
        
        # Gait mode radios
        self._create_radio_group(
            client, "gait",
            ["Radio_Gait_1", "Radio_Gait_2", "Radio_Gait_3"],
            ["Gait 1", "Gait 2", "Gait 3"],
            (40, 650, 120, 20), 120, 0, 1)
    
    def _create_radio_group(self, parent, prefix, names, texts, start_pos, spacing, initial_index, vertical_spacing=0):
        """Helper to create a group of radio buttons."""
        x, y, w, h = start_pos
        for i, (name, text) in enumerate(zip(names, texts)):
            btn = self._fx.create_radio_button(
                parent, f"{prefix}_{i+1}", text, 
                (x + (i * spacing), y, w, h))
            setattr(self.ui, name, btn)
            y += h + vertical_spacing
    
    def _create_power_indicators(self, client):
        """Create power level indicators."""
        # Power bar 1
        self.ui.progress_Power1 = QtWidgets.QProgressBar(client)
        self.ui.progress_Power1.setGeometry(QtCore.QRect(45, 705, 120, 20))
        self.ui.progress_Power1.setProperty("value", 100)
        self.ui.progress_Power1.setFormat("")
        self.ui.progress_Power1.setObjectName("progress_Power1")
        
        # Power bar 2
        self.ui.progress_Power2 = QtWidgets.QProgressBar(client)
        self.ui.progress_Power2.setGeometry(QtCore.QRect(45, 755, 120, 20))
        self.ui.progress_Power2.setProperty("value", 100)
        self.ui.progress_Power2.setFormat("")
        self.ui.progress_Power2.setObjectName("progress_Power2")
    
    def _setup_z_order(self):
        """Set the z-order of widgets to ensure proper layering."""
        # Ensure video is at the bottom
        self.ui.Video.lower()
        
        # Bring controls to front
        for widget in [
            self.ui.Button_Calibration, 
            self.ui.lineEdit_IP_Adress,
            self.ui.Button_Connect,
            self.ui.Button_Video,
            # Add other widgets that need to be on top
        ]:
            if hasattr(widget, 'raise_'):
                widget.raise_()


class Ui_client(object):
    def setupUi(self, client):
        client.setObjectName("client")
        client.resize(1000, 800)
        font = QtGui.QFont()
        font.setFamily("Arial")
        client.setFont(font)
        # Apply global styles from external QSS files (reduces inline walls of text)
        try:
            styles_dir = os.path.join(os.path.dirname(__file__), "styles")
            qss_contents = []
            for name in sorted(os.listdir(styles_dir)):
                if name.endswith(".qss"):
                    with open(os.path.join(styles_dir, name), "r", encoding="utf-8") as f:
                        qss_contents.append(f.read())
            if qss_contents:
                client.setStyleSheet("\n".join(qss_contents))
        except Exception:
            # If stylesheet load fails, continue without altering functionality
            pass
        client.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        # --- Initialize shared styles and fonts (readability improvement; no behavior change) ---
        self._init_fonts()
        # --- Initialize shared geometry values (readability; no behavior change) ---
        self._init_geo()
        # Compose factory for widget creation
        self._fx = UiFactory(self)
        # --- Video display ---
        self.Video = self._fx.create_label(client, "Video", "", (10, 10, 600, 450))
        self.Video.setFont(QtGui.QFont("Arial", 9))
        self.Video.setStyleSheet("font: 10pt \"Arial\";")
        self.Video.setText("")
        self.Video.setObjectName("Video")
        # --- Buttons (top/right controls) ---
        self.Button_Buzzer = self._fx.make_button(client, "Button_Buzzer", self._geo["Button_Buzzer"])
        self.lineEdit_IP_Adress = self._fx.create_line_edit(client, "lineEdit_IP_Adress", "192.168.1.121", (160, 470, 90, 30))
        self.Button_Connect = self._fx.make_button(client, "Button_Connect", (280, 470, 90, 30))
        self.Button_Video = self._fx.make_button(client, "Button_Video", (400, 470, 90, 30))
        self.Button_IMU = self._fx.make_button(client, "Button_IMU", self._geo["Button_IMU"])
        self.Button_Calibration = self._fx.make_button(client, "Button_Calibration", (40, 470, 90, 30))
        self.Button_Sonic = self._fx.make_button(client, "Button_Sonic", self._geo["Button_Sonic"])
        self.Button_LED = self._fx.make_button(client, "Button_LED", self._geo["Button_LED"])
        # --- IMU/Attitude labels ---
        self.label_6 = self._fx.create_label(client, "label_6", "Roll", (913, 75, 30, 20))
        self.label_attitude = self._fx.create_label(client, "label_attitude", "Attitude", (801, 185, 60, 20))
        self.label_roll = self._fx.create_label(client, "label_roll", "0", (911, 255, 30, 20))
        self.label_Y = self._fx.create_label(client, "label_Y", "Y", (891, 285, 30, 20))
        self.label_Y_2 = self._fx.create_label(client, "label_Y_2", "0", (786, 285, 30, 20))
        self.label_Y_3 = self._fx.create_label(client, "label_Y_3", "-15", (686, 285, 30, 20))
        self.label_Y_4 = self._fx.create_label(client, "label_Y_4", "(Yaw)", (921, 285, 40, 20))
        # --- Position labels ---
        self.label_X = self._fx.create_label(client, "label_X", "-15", (665, 265, 30, 20))
        self.label_X_2 = self._fx.create_label(client, "label_X_2", "0", (665, 170, 30, 20))
        self.label_X_3 = self._fx.create_label(client, "label_X_3", "15", (665, 74, 30, 20))
        self.label_X_4 = self._fx.create_label(client, "label_X_4", "(Pitch)", (645, 90, 50, 20))
        self.label_X_5 = self._fx.create_label(client, "label_X_5", "Attitude", (736, 54, 131, 20))
        # --- Sonic label ---
        self.label_sonic = self._fx.create_label(client, "label_sonic", "Obstacle:0cm", (870, 355, 120, 30))
        # --- Footer labels ---
        self.label_Y_5 = self._fx.create_label(client, "label_Y_5", "(X)", (917, 751, 40, 20))
        self.label_Y_6 = self._fx.create_label(client, "label_Y_6", "-40", (686, 751, 30, 20))
        self.label_X_6 = self._fx.create_label(client, "label_X_6", "40", (665, 545, 30, 20))
        self.label_Y_7 = self._fx.create_label(client, "label_Y_7", "0", (786, 751, 30, 20))
        self.label_X_7 = self._fx.create_label(client, "label_X_7", "0", (665, 640, 30, 20))
        self.label_Y_8 = self._fx.create_label(client, "label_Y_8", "40", (891, 751, 30, 20))
        self.label_X_8 = self._fx.create_label(client, "label_X_8", "-40", (665, 735, 30, 20))
        # --- Position title ---
        self.label_position = self._fx.create_label(client, "label_position", "(0,0)", (801, 655, 60, 20))
        self.label_X_9 = self._fx.create_label(client, "label_X_9", "(Y)", (650, 560, 40, 20))
        self.label_X_10 = self._fx.create_label(client, "label_X_10", "Position", (736, 525, 130, 20))
        # --- Sliders ---
        self.slider_roll = self._fx.create_slider(client, "slider_roll", (916, 105, 20, 140), QtCore.Qt.Vertical, -20, 20, 0)
        self.slider_Z = self._fx.create_slider(client, "slider_Z", (916, 580, 20, 140), QtCore.Qt.Vertical, -40, 40, 0)
        # --- Slider labels ---
        self.label_Z = self._fx.create_label(client, "label_Z", "0", (911, 725, 30, 20))
        self.label_9 = self._fx.create_label(client, "label_9", "Z", (913, 556, 30, 20))
        # --- Face controls ---
        self.Button_Face_ID = self._fx.make_button(client, "Button_Face_ID", (40, 510, 90, 30))
        self.Button_Face_Recognition = self._fx.make_button(client, "Button_Face_Recognition", (630, 355, 90, 30))
        # --- Relax control ---
        self.Button_Relax = self._fx.make_button(client, "Button_Relax", (520, 470, 90, 30))
        # --- Head controls ---
        self.slider_head_1 = self._fx.create_slider(client, "slider_head_1", (245, 765, 160, 20), QtCore.Qt.Horizontal, 0, 180, 90)
        self.label_head_1 = self._fx.create_label(client, "label_head_1", "90", (410, 765, 30, 20))
        self.label_10 = self._fx.create_label(client, "label_10", "Head", (195, 765, 50, 20))
        self.label_8 = self._fx.create_label(client, "label_8", "Head", (480, 555, 30, 16))
        self.slider_head = self._fx.create_slider(client, "slider_head", (485, 572, 20, 160), QtCore.Qt.Vertical, 0, 180, 90)
        self.label_head = self._fx.create_label(client, "label_head", "90", (480, 732, 30, 20))
        # --- Speed control ---
        self.label_7 = self._fx.create_label(client, "label_7", "Speed", (553, 555, 36, 16))
        self.label_speed = self._fx.create_label(client, "label_speed", "8", (563, 732, 16, 16))
        self.slider_speed = self._fx.create_slider(client, "slider_speed", (560, 572, 20, 160), QtCore.Qt.Vertical, 2, 10, 8)
        # --- Power bars ---
        self.progress_Power1 = QtWidgets.QProgressBar(client)
        self.progress_Power1.setGeometry(QtCore.QRect(45, 705, 120, 20))
        self.progress_Power1.setProperty("value", 100)
        self.progress_Power1.setFormat("")
        self.progress_Power1.setObjectName("progress_Power1")
        self.progress_Power2 = QtWidgets.QProgressBar(client)
        self.progress_Power2.setGeometry(QtCore.QRect(45, 755, 120, 20))
        self.progress_Power2.setProperty("value", 100)
        self.progress_Power2.setFormat("")
        self.progress_Power2.setObjectName("progress_Power2")
        # --- Radio buttons: Action Modes ---
        self.layoutWidget = QtWidgets.QWidget(client)
        self.layoutWidget.setGeometry(QtCore.QRect(25, 620, 121, 60))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.ButtonActionMode1 = self._fx.make_radio(self.layoutWidget, "ButtonActionMode1")
        self.verticalLayout.addWidget(self.ButtonActionMode1)
        self.ButtonActionMode2 = self._fx.make_radio(self.layoutWidget, "ButtonActionMode2")
        self.verticalLayout.addWidget(self.ButtonActionMode2)
        # --- Radio buttons: Gait Modes ---
        self.layoutWidget1 = QtWidgets.QWidget(client)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 550, 111, 60))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.ButtonGaitMode1 = self._fx.make_radio(self.layoutWidget1, "ButtonGaitMode1")
        self.verticalLayout_2.addWidget(self.ButtonGaitMode1)
        self.ButtonGaitMode2 = self._fx.make_radio(self.layoutWidget1, "ButtonGaitMode2")
        self.verticalLayout_2.addWidget(self.ButtonGaitMode2)
        # --- Status labels ---
        self.label_RasPi = self._fx.create_label(client, "label_RasPi", "RasPi", (10, 757, 30, 15))
        self.label_Load = self._fx.create_label(client, "label_Load", "Load", (10, 707, 30, 15))
        # --- Z-ordering (readability: centralized) ---
        self._z_order()

        self.retranslateUi(client)
        QtCore.QMetaObject.connectSlotsByName(client)

    def retranslateUi(self, client):
        _translate = QtCore.QCoreApplication.translate
        client.setWindowTitle(_translate("client", "Freenove Client for Hexapod"))
        self.Button_Buzzer.setText(_translate("client", "Buzzer"))
        self.lineEdit_IP_Adress.setText(_translate("client", "192.168.1.121"))
        self.Button_Connect.setText(_translate("client", "Connect"))
        self.Button_Video.setText(_translate("client", "Open Video"))
        self.Button_IMU.setText(_translate("client", "Balance"))
        self.Button_Calibration.setText(_translate("client", "Calibration"))
        self.Button_Sonic.setText(_translate("client", "Sonic"))
        self.Button_LED.setText(_translate("client", "LED"))
        self.label_6.setText(_translate("client", "Roll"))
        self.label_attitude.setText(_translate("client", "(0,0)"))
        self.label_roll.setText(_translate("client", "0"))
        self.label_Y.setText(_translate("client", "15"))
        self.label_Y_2.setText(_translate("client", "0"))
        self.label_Y_3.setText(_translate("client", "-15"))
        self.label_Y_4.setText(_translate("client", "(Yaw)"))
        self.label_X.setText(_translate("client", "-15"))
        self.label_X_2.setText(_translate("client", "0"))
        self.label_X_3.setText(_translate("client", "15"))
        self.label_X_4.setText(_translate("client", "(Pitch)"))
        self.label_X_5.setText(_translate("client", "Attitude"))
        self.label_sonic.setText(_translate("client", "Obstacle:0cm"))
        self.label_Y_5.setText(_translate("client", "(X)"))
        self.label_Y_6.setText(_translate("client", "-40"))
        self.label_X_6.setText(_translate("client", "40"))
        self.label_Y_7.setText(_translate("client", "0"))
        self.label_X_7.setText(_translate("client", "0"))
        self.label_Y_8.setText(_translate("client", "40"))
        self.label_X_8.setText(_translate("client", "-40"))
        self.label_position.setText(_translate("client", "(0,0)"))
        self.label_X_9.setText(_translate("client", "(Y)"))
        self.label_X_10.setText(_translate("client", "Position"))
        self.label_Z.setText(_translate("client", "0"))
        self.label_9.setText(_translate("client", "Z"))
        self.Button_Face_ID.setText(_translate("client", "Face ID"))
        self.Button_Face_Recognition.setText(_translate("client", "Face Recog"))
        self.Button_Relax.setText(_translate("client", "Relax"))
        self.Button_Take_Photo.setText(_translate("client", "Take photo"))
        self.label_head_1.setText(_translate("client", "90"))
        self.label_10.setText(_translate("client", "Head"))
        self.label_8.setText(_translate("client", "Head"))
        self.label_head.setText(_translate("client", "90"))
        self.label_7.setText(_translate("client", "Speed"))
        self.label_speed.setText(_translate("client", "8"))
        self.ButtonActionMode1.setText(_translate("client", "Action Mode 1"))
        self.ButtonActionMode2.setText(_translate("client", "Action Mode 2"))
        self.ButtonGaitMode1.setText(_translate("client", "Gait Mode 1"))
        self.ButtonGaitMode2.setText(_translate("client", "Gait Mode 2"))
        self.label_RasPi.setText(_translate("client", "RasPi"))
        self.label_Load.setText(_translate("client", "Load"))

    # -------------------------
    # Internal helpers (readability only; no behavior change)
    # -------------------------
    def _init_fonts(self):
        """Prepare shared fonts/styles to reduce duplication in setupUi.
        Note: Existing widgets still set their own fonts as generated; this
        helper is future-facing for consistency and readability.
        """
        # Common 9pt Arial used throughout
        self._font9 = QtGui.QFont()
        self._font9.setFamily("Arial")
        self._font9.setPointSize(9)
        self._font9.setBold(False)
        self._font9.setItalic(False)
        self._font9.setWeight(50)

        # Common button style used by all QPushButtons
        self._btn_style = "font: 10pt \"Arial\";"

    def _init_geo(self):
        """Central geometry mapping for key buttons to avoid magic numbers in code.
        Values exactly match the original UI positions.
        """
        self._geo = {
            "Button_LED": (750, 355, 90, 30),
            "Button_IMU": (630, 425, 90, 30),
            "Button_Sonic": (880, 425, 90, 30),
            "Button_Buzzer": (750, 425, 90, 30),
            "Button_Take_Photo": (750, 470, 90, 30),
        }

    def _z_order(self):
        """Centralize widget stacking order to keep setupUi terse."""
        self.Video.raise_()
        self.Button_Buzzer.raise_()
        self.lineEdit_IP_Adress.raise_()
        self.Button_Connect.raise_()
        self.Button_Video.raise_()
        self.Button_IMU.raise_()
        self.Button_Calibration.raise_()
        self.Button_Sonic.raise_()
        self.Button_LED.raise_()
        self.label_6.raise_()
        self.label_attitude.raise_()
        self.label_roll.raise_()
        self.label_Y.raise_()
        self.label_Y_2.raise_()
        self.label_Y_3.raise_()
        self.label_Y_4.raise_()
        self.label_X.raise_()
        self.label_X_2.raise_()
        self.label_X_3.raise_()
        self.label_X_4.raise_()
        self.label_X_5.raise_()
        self.label_sonic.raise_()
        self.label_Y_5.raise_()
        self.label_Y_6.raise_()
        self.label_X_6.raise_()
        self.label_Y_7.raise_()
        self.label_X_7.raise_()
        self.label_Y_8.raise_()
        self.label_X_8.raise_()
        self.label_position.raise_()
        self.label_X_9.raise_()
        self.label_X_10.raise_()
        self.slider_roll.raise_()
        self.slider_Z.raise_()
        self.label_Z.raise_()
        self.label_9.raise_()
        self.Button_Face_ID.raise_()
        self.Button_Face_Recognition.raise_()
        self.Button_Relax.raise_()
        self.slider_head_1.raise_()
        self.label_head_1.raise_()
        self.label_10.raise_()
        self.label_8.raise_()
        self.slider_head.raise_()
        self.label_head.raise_()
        self.label_7.raise_()
        self.label_speed.raise_()
        self.slider_speed.raise_()
        self.progress_Power2.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.label_RasPi.raise_()
        self.label_Load.raise_()
        self.progress_Power1.raise_()
        self.Button_Take_Photo.raise_()
